# Generated by Django 5.0.1 on 2024-01-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homecareapp.usertype'),
        ),
    ]
