# Generated by Django 5.0.1 on 2024-02-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecareapp', '0002_usertype_alter_appuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=4000)),
                ('website_url', models.CharField(max_length=1000)),
                ('rating', models.FloatField(null=True)),
                ('services', models.CharField(max_length=4000)),
                ('email', models.CharField(max_length=1000)),
                ('contact_number1', models.CharField(max_length=1000)),
                ('contact_number2', models.CharField(blank=True, max_length=1000, null=True)),
                ('address_line1', models.CharField(max_length=1000)),
                ('address_line2', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
