# Generated by Django 5.0.1 on 2024-02-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecareapp', '0003_careservice_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='details',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
