# Generated by Django 5.0.1 on 2024-03-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecareapp', '0009_alter_serviceprovider_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='provideruser',
            name='last_name',
        ),
    ]
